-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 12:22:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema obsstjean
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema obsstjean
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `obsstjean` DEFAULT CHARACTER SET utf8 ;
USE `obsstjean` ;

-- -----------------------------------------------------
-- Table `obsstjean`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obsstjean`.`users` ;

CREATE TABLE IF NOT EXISTS `obsstjean`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `obsstjean`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obsstjean`.`events` ;

CREATE TABLE IF NOT EXISTS `obsstjean`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NOT NULL,
  `date` DATETIME NOT NULL,
  `site` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
